[package]
name = "sonic-platform"
version = "0.1.0"
edition = "2021"

[dependencies]
sonic-thermalctld = { path = "../../../../src/sonic-platform-daemons/crates/sonic-thermalctld" }

anyhow = "1"
thiserror = "1"
tracing = "0.1"

glob = "0.3"
regex = "1"
